services:
  # Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: epayco_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epayco_wallet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Backend (NestJS)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epayco_api
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: epayco_wallet
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (React)
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: epayco_client
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

volumes:
  db_data:
